name: CDelivery for Hello World

on: [push, pull_request]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install Libraries
      run: |
        pip install flake8 pytest pytest-cov
    - name: Checkout Own Repo
      uses: actions/checkout@v2
      with:
        repository: DevOps-Team5-2022/DevOps_Oct2022_Team5_Week6
    - name: list our contents
      run: |
        ls
        
    - name: send message
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        color: "#48f442"
        username: "GitHub Bot"
        message: "A new commit has been made by Someone. Commit message: ${{ github.event.head_commit.message }}"
